#!/usr/bin/env bash

ACTION=all
if [ $# -gt 0 ]; then
    ACTION=$1
fi

shift

if [ "${ACTION}" != "all" -a "${ACTION}" != "test" -a "${ACTION}" != "deploy" -a "${ACTION}" != "cleanup" -a "${ACTION}" != 'unit' -a "${ACTION}" != 'upgrade' ]; then
  echo "Usage: run [unit | test | deploy | cleanup | upgrade] [EXTRA ANSIBLE ARGS]"
  exit 1
fi

source $(dirname $0)/common

cd ${ROOT}

if [ "${ACTION}" == "all" -o "${ACTION}" == "deploy" ]; then
  time ursula "envs/test" site.yml -u ${LOGIN_USER} --sudo "$@"
  ring_bell
fi

if [ "${ACTION}" == "all" -o "${ACTION}" == "test" ]; then
  time ursula "envs/test" ${ROOT}/playbooks/tests/tasks/main.yml -u ${LOGIN_USER} --sudo  $@
  ring_bell
fi

if [ "${ACTION}" == "all" -o "${ACTION}" == "cleanup" ]; then
  time ursula "envs/test" ${ROOT}/playbooks/tests/tasks/cleanup.yml -u ${LOGIN_USER} --sudo
  ring_bell
fi

if [ "${ACTION}" == "upgrade" ]; then
  time ursula "envs/test" upgrade.yml -u ${LOGIN_USER} --sudo "$@"
  ring_bell
fi

echo "test complete"
