---
- name: check if cinder user exists
  shell: getent passwd cinder
  register: cinder_user
  failed_when: False
  changed_when: False

- name: cinder user
  user: name=cinder shell=/bin/false createhome=no
  when: cinder_user|success

- name: cinder user
  user: name=cinder comment=cinder shell=/bin/false system=yes
        home=/nonexistent createhome=no
  when: not cinder_user|success

- name: /etc/cinder
  file: dest=/etc/cinder state=directory

- name: cinder lib dirs
  file: dest={{ item }} state=directory owner=cinder group=cinder
  with_items:
    - /var/lib/cinder
    - /var/lib/cinder/images

- name: cinder cache dir
  file: dest=/var/cache/cinder state=directory mode=0700 owner=cinder
        group=cinder

- name: cinder log dir
  file: dest=/var/log/cinder state=directory mode=0755 owner=cinder group=cinder

- name: cinder config
  template: src={{ item }} dest=/etc/cinder mode=0644
  with_fileglob: ../templates/etc/cinder/*
  notify: restart cinder services

- name: cinder sudoer
  template: src=etc/sudoers.d/cinder dest=/etc/sudoers.d/cinder owner=root
            group=root mode=0440

- include: logging.yml
  tags:
    - logrotate
    - logging
