---
- name: remove older libruby
  apt: pkg=libruby1.8 purge=yes state=absent

- name: install system tools
  apt: pkg={{ item }}
  with_items:
    - ack-grep
    - build-essential
    - curl
    - dstat
    - ethtool
    - git
    - htop
    - iotop
    - iperf
    - ltrace
    - mcelog
    - mtr
    - netcat
    - pstack
    - pv
    - ruby1.9.1
    - ruby1.9.1-dev
    - smem
    - socat
    - tree
    - vim
    - cdpr
    - sysstat
    - logrotate
    - ipmitool
    - ntp
    - vlan

- name: load vlan module
  lineinfile: dest=/etc/modules
              line="8021q"
  when: ansible_distribution_version == "14.04"

# http://www.supermicro.com/support/faqs/faq.cfm?faq=14537
- name: blacklist mei
  lineinfile: dest=/etc/modprobe.d/blacklist.conf
              line="blacklist {{ item }}"
  with_items:
    - mei
    - mei_me

- name: install lm-sensors package
  apt: name=lm-sensors state=present update_cache=yes
  notify:
    - load sensors

- meta: flush_handlers
