---
- name: keystone process check
  sensu_process_check: service=keystone-all
  notify: restart sensu-client

- name: keystone-api check
  sensu_check: name=check-keystone-api plugin=check-os-api.rb
               args="--service keystone"
  notify: restart sensu-client

- name: keystone token buildup check
  sensu_check:
    name: check-keystone-expired-tokens
    plugin: check-keystone-expired-tokens.py
    interval: 10
    use_sudo: true
  notify: restart sensu-client

- name: keystone metrics
  template: src=etc/collectd/plugins/keystone.conf dest=/etc/collectd/plugins/keystone.conf
  notify: restart collectd
  when: collectd is defined and collectd.enabled|bool
  tags: collectd
